"""
vcf_to_mutalyzer.py
===================
Reads the VCF produced by bed_to_vcf.py and writes a Mutalyzer batch
input file (one HGVS genomic notation per line).

Usage:  python3 vcf_to_mutalyzer.py

Output (written alongside the VCF):
  mutalyzer_batch_input.txt  — upload to https://mutalyzer.nl/batch-jobs
                               Job type: Position Converter
"""

import os, re

# ── Configuration ──────────────────────────────────────────────────────────────
VCF_PATH  = "/home/khoi1996/Documents/BED/hg38/all_variants_hg38.vcf"
OUT_PATH  = "/home/khoi1996/Documents/BED/hg38/mutalyzer_batch_input.txt"

# ── hg38 chr → NC_ accession (GRCh38.p14) ─────────────────────────────────────
CHR_TO_NC = {
    "chr1":  "NC_000001.11", "chr2":  "NC_000002.12", "chr3":  "NC_000003.12",
    "chr4":  "NC_000004.12", "chr5":  "NC_000005.10", "chr6":  "NC_000006.12",
    "chr7":  "NC_000007.14", "chr8":  "NC_000008.11", "chr9":  "NC_000009.12",
    "chr10": "NC_000010.11", "chr11": "NC_000011.10", "chr12": "NC_000012.12",
    "chr13": "NC_000013.11", "chr14": "NC_000014.9",  "chr15": "NC_000015.10",
    "chr16": "NC_000016.10", "chr17": "NC_000017.11", "chr18": "NC_000018.10",
    "chr19": "NC_000019.10", "chr20": "NC_000020.11", "chr21": "NC_000021.9",
    "chr22": "NC_000022.11", "chrX":  "NC_000023.11", "chrY":  "NC_000024.10",
    "chrM":  "NC_012920.1",
}

RE_G_RANGE = re.compile(r"g\.(\d+)_(\d+)(?:del|dup)", re.I)
RE_INFO    = re.compile(r"GENE=([^;]+).*?SRC=([^;]+)")


def vcf_to_hgvs(chrom, pos, ref, alt, name):
    """Convert a VCF row to an HGVS genomic string."""
    nc = CHR_TO_NC.get(chrom)
    if not nc:
        return None

    # SNV
    if len(ref) == 1 and len(alt) == 1 and ref not in "N." and alt not in ("N", ".", "DUP"):
        return f"{nc}:g.{pos}{ref}>{alt}"

    # Range deletion / duplication (no sequence, sentinels "." and "DUP")
    if alt in (".", "DUP"):
        m = RE_G_RANGE.search(name)
        span = int(m.group(2)) - int(m.group(1)) if m else 0
        op = "del" if alt == "." else "dup"
        return f"{nc}:g.{pos}_{pos+span}{op}" if span else f"{nc}:g.{pos}{op}"

    # Insertion / dup with sequence: REF=N, ALT=Nxxx
    if ref == "N" and alt.startswith("N") and len(alt) > 1:
        ins = alt[1:]
        if "dup" in name.lower():
            return (f"{nc}:g.{pos}_{pos+len(ins)-1}dup" if len(ins) > 1
                    else f"{nc}:g.{pos}dup")
        return f"{nc}:g.{pos-1}_{pos}ins{ins}"

    # Deletion with sequence: REF=Nxxx, ALT=N
    if ref.startswith("N") and len(ref) > 1 and alt == "N":
        d = ref[1:]
        return f"{nc}:g.{pos+1}del" if len(d) == 1 else f"{nc}:g.{pos+1}_{pos+len(d)}del"

    # Delins: REF=N, ALT=plain sequence
    if ref == "N" and alt not in ("N", ".", "DUP"):
        return f"{nc}:g.{pos}delins{alt}"

    # Fallback
    return f"{nc}:g.{pos}_{pos+max(len(ref),1)-1}del{ref}ins{alt}"


def main():
    print(f"VCF → Mutalyzer batch  |  source: {VCF_PATH}\n")

    written = skipped = 0
    with open(VCF_PATH, encoding="utf-8") as vcf, \
         open(OUT_PATH,  "w", encoding="utf-8") as out:

        out.write("# Mutalyzer batch input — generated by vcf_to_mutalyzer.py\n"
                  "# Submit at: https://mutalyzer.nl/batch-jobs\n"
                  "# Job type: Position Converter\n\n")

        for line in vcf:
            if line.startswith("#"): continue
            parts = line.rstrip().split("\t")
            if len(parts) < 8: continue

            chrom, pos, name, ref, alt, _, _, info = parts[:8]
            pos = int(pos)

            m = RE_INFO.search(info)
            gene = m.group(1) if m else ""

            hgvs = vcf_to_hgvs(chrom, pos, ref, alt, name)
            if hgvs:
                out.write(f"{hgvs}\t# {gene}  {name}\n")
                written += 1
            else:
                skipped += 1

    print(f"Mutalyzer batch  : {OUT_PATH}  ({written} entries, {skipped} skipped)")
    print("\nNext steps:")
    print("  1. Go to https://mutalyzer.nl/batch-jobs")
    print("  2. Upload mutalyzer_batch_input.txt")
    print("  3. Job type: 'Position Converter'")
    print("  4. Enter your email — results give c. and p. notations for LOVD")


if __name__ == "__main__":
    main()